### PR TITLE
Various code quality refactors for login/creation experience.

### PR DESCRIPTION
**Pull request by krashanoff**
Been meaning to do this for a while. Now that we're moving towards SQLite and the grading system is mostly done (*kind of*) I am going to need to poke my nose into frontend. This is a fairly large overhaul to the user creation component family. Instead of having two sign up forms with code duplication, this merges them into a single stateful form. Tested for functionality before opening PR.

This PR has a lot of changes. It might not be so easy on the eyes. I recommend just checking out the branch and seeing what the `AccountCreation` folder looks like.

## Summary

* Delete SignUpProfessor.
* Delete SignUpStudent.
* Create SignUpForm. Merge signup component shared behavior.
* Remove extraneous routes in App.tsx.
* Refactor Login.tsx to avoid async.
* Direct component imports to optimize bundle size.
* Use of `===` and `!==` in components.
* Removal of redundant error handling.

### CODE REVIEW

**Comment by 1strangequark** [comment]
One issue I discovered while using this branch is that, after creating an account, the "Account Created Successfully" modal no longer appears. As a result, the user cannot close this modal and get navigated to the class page.

I would introduce a call to invoke this modal after receiving a successful response from the backend.

**Comment by 1strangequark** [comment]
Other than that, the code looks clean and the refactor appears to work well.

**Review by cindyrzheng — APPROVED** [review]
lgtm

**Comment by krashanoff** [comment]
I'll just push a hot fix for the modal popup post-backend request.

**Comment by krashanoff** [comment]
Done in 2e93d120f86dd8294b0312c7dc11089aa441ee37.

**Pull request merged**
