### PR TITLE
Migrate database to SQLite.

### PR DESCRIPTION
**Pull request by krashanoff**
Found a big bug in the leading Postgres driver, so this PR switches our schemas to SQLite. It also removes the trigger for password hashing and such. We just use [argon2](https://en.wikipedia.org/wiki/Argon2) instead.

This means that Docker is no longer necessary, nor is a postgresql installation. All your database information is just in a single file.

## Important Changes

* You should have GCC installed for building the backend with SQLite.
* You need to have `make` installed.
* You can now check the state of your database with `sqlite3 test.db` after running the backend once.

## New Features

* Adds `-D` flag to reset the database schema.

### CODE REVIEW

**Comment by edwardsabalburo** [comment]
I checked out this branch and did some local testing and all my previous curl commands work! One minor issue though is that I cannot start the backend and rerun it (see screenshot), but the issue can be resolved manually by just dropping all tables  through the sqlite3 command line before running again.

image

**Comment by edwardsabalburo** [comment]
Just another issue I found while testing... Whenever I insert into the database using the sqlite3 command line, the response data is not reflecting the actual database values. So far I've only encountered this with the GET assignment endpoints (using the login/account creation endpoints worked fine).

image

**Comment by krashanoff** [comment]
Might be a consistency issue, but it's probably nothing serious. Right now its hard-coded to reset the database on startup. I'll be making that a CLI flag in the next commit though.

**Comment by krashanoff** [comment]
Fixed how we handle datetimes in the assignment handlers at least.

**Comment by krashanoff** [comment]
Force-merging for brevity.

**Pull request merged**
